# Generated by Django 6.0.1 on 2026-01-09 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='departement',
            name='code_departement',
            field=models.CharField(default='DEPT001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_dirige', to='core.enseignant'),
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_contenu', models.CharField(choices=[('cours', 'Cours'), ('exercice', 'Exercice')], default='cours', max_length=20)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_crees', to='core.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_set', to='core.matiere')),
            ],
            options={
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_marquees', to='core.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.matiere')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('eleve', 'matiere', 'date')},
            },
        ),
    ]
